os:
  - linux
  - osx
language: c
install:
  - mkdir -p deps/OpenCL-Headers
  - git clone https://github.com/KhronosGroup/OpenCL-Headers deps/OpenCL-Headers/CL
compiler:
  - gcc
script:
  - make
  - perl tools/test.pl
  - tools/test.sh